[pytest]
DJANGO_SETTINGS_MODULE = telemetry_validator.settings
python_files = test_*.py

pythonpath = . app

addopts = --reuse-db

markers =
    smoke: critical smoke tests
    integration: integration tests covering full request flows
